name: m3allim
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
 # validator: ">=0.0.4 <0.1.0"
  flutter:
    sdk: flutter
  #firebase_auth: ^0.8.3
  cloud_firestore: ^0.9.7
  firebase_auth: ^0.8.4+2

  #firebase_auth: ^0.8.1+1
  #firebase_core: ^0.2.5
  flutter_rating: ^0.0.2
  url_launcher: ^5.0.2
  image_picker: 0.5.0+9
  fluttertoast: ^3.0.3
  geolocator: ^3.0.1
  carousel_slider: ^1.3.0
  curved_navigation_bar: ^0.1.2 #latest version
  cupertino_icons: ^0.1.2
  flutter_search_bar: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/crown.png
    - assets/hands.png
    - assets/diamond.png
    - assets/diamondYellow.png
    - assets/handsYellow.png
    - assets/crownYellow.png
    - assets/logo.PNG
    - assets/mech.jpg
    - assets/general.jpg
    - assets/immune.jpg
    - assets/nerve.jpg
    - assets/nose.jpg
    - assets/skin.jpg
    - assets/tooth.jpg
    - assets/women.jpg
    - assets/hadme.jpg
    - assets/barbermen.jpg
    - assets/constructor.jpg
    - assets/hdresser.jpg
    - assets/tailor.jpg
    - assets/carpet.png
    - assets/barberwomen.jpg
    - assets/bostane.jpg
    - assets/mechanic.jpg
    - assets/kahrbge.jpg
    - assets/hadad.jpg
    - assets/hearty.jpg
    - assets/doctor.jpg
    - assets/furniture.jpg
    - assets/highSchool.jpg
    - assets/designImage.jpg
    - assets/elementary.jpg
    - assets/tutor.jpg
    - assets/midSchool.jpg
    - assets/uniStudent.jpg
    - assets/dahan.jpg
    - assets/plumber.jpg
    - assets/photo.jpg
    - assets/realEstate.jpg
    - assets/shoe.jpg
    - assets/bostani.jpeg
    - assets/handy.png
    - assets/crowny.png
    - assets/diamondy.png
    - assets/hnew.png
    - assets/dnew.png
    - assets/cnew.png
    - assets/ballat.jpg

    
    
    #- assets/insertImage.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
